apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-two
  name: service-two
spec:
  type: NodePort # verificar types possiveis
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: service-two