apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-one
  name: service-one
spec:
  type: NodePort # verificar types possiveis
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: service-one